CREATE DATABASE [PRUEBA_API]
GO
USE [PRUEBA_API]
GO
/****** Object:  Table [dbo].[PERSONA]    Script Date: 23/12/2022 8:12:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSONA](
	[ID_PERSONA] [bigint] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [nvarchar](50) NULL,
	[APELLIDO] [nvarchar](50) NULL,
	[NOMBRE_COMPLETO] [nvarchar](100) NULL,
	[TIPO_IDENTIFICACION] [nvarchar](50) NULL,
	[NUMERO_IDENTIFICACION] [nvarchar](50) NULL,
	[NUMERO_IDENTIFICACION_TIPO] [nvarchar](100) NULL,
	[EMAIL] [nvarchar](50) NULL,
	[FECHA_CREACION] [datetime] NULL,
 CONSTRAINT [PK_PERSONAS] PRIMARY KEY CLUSTERED 
(
	[ID_PERSONA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 23/12/2022 8:12:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[ID_USUARIO] [bigint] IDENTITY(1,1) NOT NULL,
	[USUARIO] [nvarchar](50) NULL,
	[PASS] [nvarchar](100) NULL,
	[FECHA_CREACION] [datetime] NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[PERSONA] ON 
GO
INSERT [dbo].[PERSONA] ([ID_PERSONA], [NOMBRE], [APELLIDO], [NOMBRE_COMPLETO], [TIPO_IDENTIFICACION], [NUMERO_IDENTIFICACION], [NUMERO_IDENTIFICACION_TIPO], [EMAIL], [FECHA_CREACION]) VALUES (1, N'Persona 1', N'Apellido 1', N'Persona 1 Apellido 1', N'cedula', N'1010101010', N'cedula 1010101010', N'email.prueba', CAST(N'2022-12-23T20:17:42.430' AS DateTime))
GO
INSERT [dbo].[PERSONA] ([ID_PERSONA], [NOMBRE], [APELLIDO], [NOMBRE_COMPLETO], [TIPO_IDENTIFICACION], [NUMERO_IDENTIFICACION], [NUMERO_IDENTIFICACION_TIPO], [EMAIL], [FECHA_CREACION]) VALUES (2, N'Persona 2', N'Apellido 2', N'Persona 2 Apellido 2', N'tarjeta', N'19242', N'tarjeta 19242', N'correo2.', CAST(N'2022-12-23T20:18:20.843' AS DateTime))
GO
INSERT [dbo].[PERSONA] ([ID_PERSONA], [NOMBRE], [APELLIDO], [NOMBRE_COMPLETO], [TIPO_IDENTIFICACION], [NUMERO_IDENTIFICACION], [NUMERO_IDENTIFICACION_TIPO], [EMAIL], [FECHA_CREACION]) VALUES (3, N'Persona 3', N'Apellido 3', N'Persona 3 Apellido 3', N'cedula', N'12347', N'cedula 12347', N'correo.3', CAST(N'2022-12-23T20:18:41.017' AS DateTime))
GO
INSERT [dbo].[PERSONA] ([ID_PERSONA], [NOMBRE], [APELLIDO], [NOMBRE_COMPLETO], [TIPO_IDENTIFICACION], [NUMERO_IDENTIFICACION], [NUMERO_IDENTIFICACION_TIPO], [EMAIL], [FECHA_CREACION]) VALUES (4, N'Persona 4', N'Apellido 4', N'Persona 4 Apellido 4', N'cedula', N'1544243', N'cedula 1544243', N'micorreo', CAST(N'2022-12-23T20:19:09.843' AS DateTime))
GO

SET IDENTITY_INSERT [dbo].[PERSONA] OFF
GO
SET IDENTITY_INSERT [dbo].[USUARIO] ON 
GO
INSERT [dbo].[USUARIO] ([ID_USUARIO], [USUARIO], [PASS], [FECHA_CREACION]) VALUES (1, N'username', N'AQAAAAEAACcQAAAAENuysOaXWpl4ZEmx6WTbxeAgiqi2bvkHjJagzV8jxND0qrXtG3kdSv04j/9kQrJ8gw==', CAST(N'2022-12-23T19:32:06.690' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[USUARIO] OFF
GO
/****** Object:  StoredProcedure [dbo].[CONSULTA_PERSONAS]    Script Date: 23/12/2022 8:12:38 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[CONSULTA_PERSONAS] 
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SELECT * FROM [dbo].[PERSONA];

	RETURN;
END
GO
